#!/bin/bash
#
# small setup script for automating configuration files

cp config/default.py.example config/default.py

sed -i s/REPLACE_SECRET_KEY/$(python -c "import uuid; print uuid.uuid4()")/g config/default.py
